#!/usr/bin/env bash
set -eu

export VERSION=0.1.0
export LIBEXEC_PATH=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
export ROOT_PATH=$(dirname ${LIBEXEC_PATH})
export LIB_PATH=${ROOT_PATH}/lib
export PATH=${LIBEXEC_PATH}:$PATH

source ${LIB_PATH}/getoptions.sh

function parser_definition_main() {
  msg -- "ghr-get ${VERSION}"
  setup REST help:usege abbr:true width:20,20 -- \
      "Usege: ghr-get [global options...] [command] [options...] [arguments...]"
  msg -- '' 'Global Options:'
  disp :usege   -h --help    -- "Show help"
  disp VERSION     --version -- "Show version"
  msg -- '' 'Commands:'
  cmd install         -- "Install package"
  cmd uninstall       -- "Uninstall package"
  cmd latest-version  -- "Show latest version"
}

function main() {
  eval "$(getoptions parser_definition_main parse) return 1"
  parse "$@"
  eval "set -- $REST"

  if [ $# -eq 0 ]; then
    exec "$0" --help
    return 0
  fi

  local -r command=$1
  local -r command_path="$(command -v "ghr-get-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "Not a command: $command"
    return 1
  fi
  shift 1
  "$command_path" "$@"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
