#!/usr/bin/env bash
# Summary: Install package
# Usage: ghr-get install PACKAGE
source $GHR_GET_ROOT/lib/common-lib.bash

package="$1"
if [[ -z "$package" ]]; then
  ghr-get help --usage install
  exit 1
fi
if [[ "$package" =~ = ]]; then
  version="${package##*=}"
  package="${package%%=*}"
else
  version="$(ghr-get latest-version "$package")" || exit 1
fi

# get package
if [[ "$version" == "" ]]; then
  echo "Install $package ..."
  package_dir="$(ghr-get-_git-clone "$package")"
else
    echo "Install $package(version $version) ..."
  package_dir="$(ghr-get-_download-package "$package" "$version")"
  ret=$?
  [[ $ret != 0 ]] && exit $ret
fi

# set plugin links
ghr-get-_link-files "$package_dir" "plugins"

# set execution links
ghr-get-_link-files "$package_dir" "bin"
