#!/usr/bin/env bash
# Summary: List packages
# Usage: ghr-get list
source $GHR_GET_ROOT/lib/common-lib.bash

for package_dir in $GHR_GET_ROOT/packages/*/*/*; do
  package=${package_dir#*/packages/*/}
  echo $package
done
