#!/usr/bin/env bash
# Summary: Install package
# Usage: ghr-get install PACKAGE
source $GHR_GET_ROOT/lib/common-lib.bash

package="$1"
version="$(ghr-get latest-version "$package")" || exit 1

# get package
if [[ "$version" == "" ]]; then
  echo "Install $package ..."
  package_dir="$(ghr-get-_git-clone "$package")"
else
  echo "Install $package@$version ..."
  package_dir="$(ghr-get-_download-package "$package" "$version")"
fi

# set execution links
ghr-get-_link-files "$package_dir" "bin"

# set plugin links
ghr-get-_link-files "$package_dir" "plugins"
