#!/usr/bin/env bash
# Summary: Show latest version
source $GHR_GET_ROOT/lib/common-lib.bash

package="$1"
if [ -z "$package" ]; then
  ghr-get-help latest-version >&2
  exit 1
fi

url=https://github.com/$package/releases/latest
html=$(curl -fsSL $url) || abort "Package '$package' is not found"

echo "$html" |
  grep -o "/$package/releases/download/[^\"]*" |
  awk -F/ '{print $6}' |
  sort |
  uniq
