#!/usr/bin/env bash
# Summary: Show latest version
source $GHR_GET_ROOT/lib/common-lib.bash

package="$1"
if [ -z "$package" ]; then
  ghr-get-help latest-version >&2
  exit 1
fi

url="$(eval echo $LATEST_PAGE_URL)"
headers=$(curl -IfsS $url) || abort "Package '$package' is not found"

echo "$headers" |
  grep '^location: ' |
  awk -F/ '{print $8}'
