#!/usr/bin/env bash
set -eu

export LIBEXEC_PATH=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))
source $LIBEXEC_PATH/ghr-get

function parser_definition() {
  setup REST help:usege abbr:true width:20,20 -- \
      "Usege: ghr-get latest-version [options...] [package name]"
  msg -- '' 'Options:'
  disp :usege   -h --help    -- "Show help"
}
eval "$(getoptions parser_definition parse) exit 1"

function main() {
  parse "$@"
  eval "set -- $REST"
  if [ $# -ne 1 ]; then
    ${BASH_SOURCE[0]} --help
    return 1
  fi

  local -r package="$1"
  local -r url=https://github.com/${package}/releases/latest
  local -r headers=$(curl -IfsS ${url} 2>&1)
  if [[ "${headers%%:*}" == "curl" ]]; then
    echo "${headers}" | head -1 >&2
    echo "package is not found: ${package}" >&2
    return 1
  fi

  local -r version=$(echo "$headers" | awk -F/ -v RS='\r\n' '/^location: / {print $8}')
  if [[ "${version}" == "" ]]; then
    echo "release package is not found: ${package}" >&2
    return 1
  fi
  echo -n ${version}
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
