#!/usr/bin/env bash
source $GHR_GET_ROOT/lib/common-lib.bash

function get_file_pattern() {
  shopt -s nocasematch
  local os arch
  case "$(uname)" in
    mingw*)
      os='\(windows\|win\).*'
      ;;
    linux*)
      os=linux
      ;;
    darwin)
      os='\(darwin\|osx\)'
      ;;
  esac
  case "$(uname -m)" in
    *64)
      arch='.*64'
      ;;
    # TODO support 386, arm, etc...
  esac

  echo [-_\\.]$os[-_\\.]\\?$arch
}

function get_release_filepath() {
  local site="$1" package="$2" version="$3"
  local url=https://$site/$package/releases/$version
  local html=$(curl -fsSL $url) || abort "Package version '$package@$version' is not found"
  local pattern=$(get_file_pattern)
  
  local file=$(echo "$html" |
    grep -o "/$package/releases/download/[^\"]*" |
    awk -F/ '{print $7}' |
    grep $pattern |
    head -1)
  [ -z "$file" ] && abort "no target architecture"

  echo "$file"
}

function download_file() {
  local url="$1" package_dir="$2"

  curl -sSL -o "$package_dir/$file" "$url"
  if [ $? -ne 0 ]; then
    # TODO uninstall package
    abort "Download error $url"
  fi
}

function unarchive_file() {
  local package="$1" package_dir="$2" file="$3"
  shopt -s nocasematch
  case "$file" in
    *.zip)
      unzip -oq $package_dir/$file -d $package_dir
      rm -f $package_dir/$file
      ;;
    *.tar.gz|*.tgz)
      tar -xz -C $package_dir -f $package_dir/$file
      rm -f $package_dir/$file
      ;;
    *)
      if (file $package_dir/$file | grep "executable" > /dev/null ); then
        # execution file
        local newname=${package##*/}
        local ext=${file##*.}
        if [ "$ext" != "" ]; then
          newname="$newname.$ext"
        fi
        mv $package_dir/$file $package_dir/$newname
        chmod a+x $package_dir/$project
      else
        echo "Unknown file type. [$file]." >&2
        return 1
      fi
      ;;
  esac
}

site="github.com"
package="$1"
version="$2"

package_dir="$GHR_GET_ROOT/packages/$site/$package/$version"
echo "$package_dir"

[[ -d "$package_dir" ]] && exit
mkdir -p "$package_dir"
  
file="$(get_release_filepath "$site" "$package" "$version")"
url="https://$site/$package/releases/download/$version/$file"
download_file "$url" "$package_dir" || exit 1
unarchive_file "$package" "$package_dir" "$file" || exit 1
